name: CD Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install & Test
        run: |
          npm ci
          npm test

      - name: Build Extension
        run: npm run build

      - name: Archive Extension Artifact
        run: |
          zip -r mqtt_dist_extension-${{ github.ref_name }}.zip mqtt_dist_extension/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: mqtt_dist_extension-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
